"""Single-owner password sessions. Passwords and session tokens are never stored raw."""
import hashlib
import hmac
import json
import os
from pathlib import Path
import re
import secrets
import sqlite3
import time
from contextlib import contextmanager

from fastapi import HTTPException, Request
from fastapi.responses import HTMLResponse, JSONResponse, RedirectResponse
from pydantic import BaseModel, ConfigDict, Field

ROOT = Path(__file__).resolve().parent/'data/auth'
COOKIE = 'nexen_session'
ITERATIONS = 600_000
SESSION_SECONDS = 12*60*60
SUPPORTED_DESTINATIONS = frozenset({
    '/', '/game', '/tasks', '/day', '/photos', '/problems', '/plans', '/lab', '/guide',
    '/money', '/lookbook', '/connections', '/voice', '/next', '/desktop', '/storage',
    '/memory-pools', '/automatic-mode', '/problem-cases', '/check-in', '/agentic-os',
    '/youtube-memory', '/code-review', '/readiness', '/kilo', '/agents', '/continuity',
    '/music-render',
})

class PasswordBody(BaseModel):
    model_config = ConfigDict(extra='forbid')
    password: str = Field(min_length=12, max_length=256)


def valid_service_key(value):
    """Accept only the complete format generated by token_urlsafe(48)."""
    return isinstance(value, str) and re.fullmatch(r'[A-Za-z0-9_-]{64}', value) is not None


class AuthStore:
    def __init__(self, root=ROOT):
        """Open the local session store and create its service key if missing."""
        self.root=Path(root)
        self.root.mkdir(parents=True, exist_ok=True)
        self.path=self.root/'sessions.sqlite3'
        with self.connect() as c:
            c.executescript('''CREATE TABLE IF NOT EXISTS owner(id INTEGER PRIMARY KEY CHECK(id=1),salt TEXT,hash TEXT,iterations INTEGER);
              CREATE TABLE IF NOT EXISTS sessions(hash TEXT PRIMARY KEY,created REAL,expires REAL);
              CREATE TABLE IF NOT EXISTS login_attempts(at REAL,success INTEGER);''')
        self.key_path=self.root/'service.key'
        # The same DB serializes every participating process. The published key
        # is never empty, and an existing key is never silently replaced.
        with self.connect() as c:
            c.execute('BEGIN IMMEDIATE')
            if not self.key_path.exists():
                self._publish_service_key()
            with self.key_path.open('rb') as source:
                raw = source.read(129)
            try:
                key = raw.decode('ascii').strip() if len(raw) <= 128 else None
            except UnicodeDecodeError:
                key = None
            if not valid_service_key(key):
                raise RuntimeError('Invalid service key; restore a complete key before starting NEXEN.')
            self.service_key = key

    def _publish_service_key(self):
        """Publish a complete key while the caller holds the initialization lock.

        The private parent's Windows ACL is inherited; POSIX mode is owner-only.
        Atomic replacement moves the already-closed file on the same volume.
        """
        temporary = self.root / ('.service-key-' + secrets.token_hex(16) + '.tmp')
        fd = os.open(temporary, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
        try:
            with os.fdopen(fd, 'w', encoding='ascii') as out:
                out.write(secrets.token_urlsafe(48))
                out.flush()
                os.fsync(out.fileno())
            os.replace(temporary, self.key_path)
        finally:
            temporary.unlink(missing_ok=True)

    @contextmanager
    def connect(self):
        """Commit successful session changes and always release the connection."""
        c=sqlite3.connect(self.path,timeout=5)
        c.row_factory=sqlite3.Row
        try:
            yield c
            c.commit()
        finally:
            c.close()

    def configured(self):
        """Report whether the single owner has initialized a password."""
        with self.connect() as c:
            return c.execute('SELECT 1 FROM owner').fetchone() is not None

    @staticmethod
    def password_hash(password,salt,iterations=ITERATIONS):
        """Derive the password hash using the stored salt and work factor."""
        return hashlib.pbkdf2_hmac('sha256',password.encode('utf-8'),bytes.fromhex(salt),iterations).hex()

    def new_session(self,c):
        """Store only the token hash; return the raw token for its cookie."""
        token=secrets.token_urlsafe(32)
        now=time.time()
        c.execute('DELETE FROM sessions WHERE expires<?',(now,))
        c.execute('INSERT INTO sessions VALUES(?,?,?)',(hashlib.sha256(token.encode()).hexdigest(),now,now+SESSION_SECONDS))
        return token

    def setup(self,password):
        """Create exactly one owner under an immediate transaction."""
        salt=secrets.token_hex(32)
        hashed=self.password_hash(password,salt)
        with self.connect() as c:
            c.execute('BEGIN IMMEDIATE')
            if c.execute('SELECT 1 FROM owner').fetchone():
                raise HTTPException(409,'A password is already set. Unlock the existing account.')
            c.execute('INSERT INTO owner VALUES(1,?,?,?)',(salt,hashed,ITERATIONS))
            return self.new_session(c)

    def login(self,password):
        """Validate the password, record failures, and issue an expiring session."""
        with self.connect() as c:
            c.execute('BEGIN IMMEDIATE')
            now=time.time()
            c.execute('DELETE FROM login_attempts WHERE at<?',(now-86400,))
            failures=c.execute('SELECT count(*) FROM login_attempts WHERE at>? AND success=0',(now-900,)).fetchone()[0]
            if failures>=5:
                raise HTTPException(429,'Too many attempts. Wait 15 minutes before trying again.')
            owner=c.execute('SELECT * FROM owner').fetchone()
            valid=bool(owner and hmac.compare_digest(self.password_hash(password,owner['salt'],owner['iterations']),owner['hash']))
            c.execute('INSERT INTO login_attempts VALUES(?,?)',(now,int(valid)))
            if valid:
                c.execute('DELETE FROM login_attempts')
                token=self.new_session(c)
            else:
                token=None
        if token is None:
            raise HTTPException(401,'The password did not match.')
        return token

    def valid(self,token):
        """Accept only an existing, unexpired session-token hash."""
        if not token or len(token)>128:
            return False
        with self.connect() as c:
            return c.execute('SELECT 1 FROM sessions WHERE hash=? AND expires>?',
                (hashlib.sha256(token.encode()).hexdigest(),time.time())).fetchone() is not None

    def logout(self,token):
        """Revoke the supplied session without affecting other owner sessions."""
        if token:
            with self.connect() as c:
                c.execute('DELETE FROM sessions WHERE hash=?',(hashlib.sha256(token.encode()).hexdigest(),))

def register(app):
    """Register password routes and return the gate used by the app middleware."""
    store=AuthStore()

    def session_response(token,request):
        """Return the session cookie with transport-appropriate security flags."""
        response=JSONResponse({'authenticated':True})
        response.set_cookie(COOKIE,token,max_age=SESSION_SECONDS,httponly=True,samesite='strict',
                            secure=bool(getattr(request.state,'private_access',False)),path='/')
        response.headers['Cache-Control']='no-store'
        return response

    @app.get('/login',response_class=HTMLResponse)
    def login_page():
        """Serve the local sign-in view."""
        return (Path(__file__).parent/'login.html').read_text(encoding='utf-8')

    @app.get('/api/auth/session')
    def session(request:Request):
        """Report authentication and permitted navigation without credentials."""
        return {'configured':store.configured(),'authenticated':store.valid(request.cookies.get(COOKIE)),
                'supported_destinations': sorted(SUPPORTED_DESTINATIONS),
                'can_setup':not getattr(request.state,'private_access',False),
                'transport':'private_https' if getattr(request.state,'private_access',False) else 'local_loopback',
                'disk_encryption':'not_configured_by_nexen'}

    @app.post('/api/auth/setup')
    def setup(body:PasswordBody,request:Request):
        """Permit first-password setup only from the owning PC."""
        if getattr(request.state,'private_access',False):
            raise HTTPException(403,'Create the first password on the NEXEN PC.')
        return session_response(store.setup(body.password),request)

    @app.post('/api/auth/login')
    def login(body:PasswordBody,request:Request):
        """Exchange the owner password for a session cookie."""
        return session_response(store.login(body.password),request)

    @app.post('/api/auth/logout')
    def logout(request:Request):
        """Revoke this session and remove its browser cookie."""
        store.logout(request.cookies.get(COOKIE))
        response=JSONResponse({'authenticated':False})
        response.delete_cookie(COOKIE,path='/')
        return response

    @app.get('/healthz')
    def health():
        """Expose loopback liveness without returning private application data."""
        return {'status':'ok'}

    def gate(request):
        """Require an owner session except for explicit public or service routes."""
        path=request.url.path
        allowed={'/login','/api/auth/session','/api/auth/setup','/api/auth/login','/api/auth/logout'}
        if path in allowed or path in ('/branding/NEXEN-logo.png','/branding/NEXEN.ico'):
            return None
        private=getattr(request.state,'private_access',False)
        if path=='/healthz' and not private:
            return None
        # A fixed loopback-only service credential keeps the watchdog functioning.
        # It cannot unlock arbitrary routes or be used through Tailscale.
        keys=request.headers.getlist('x-nexen-service')
        service_paths={'/api/hub/digest','/api/memory/context','/api/lab/chat','/api/hub/request'}
        if not private and path in service_paths and len(keys)==1 and valid_service_key(store.service_key) and hmac.compare_digest(keys[0].encode('utf-8'),store.service_key.encode('utf-8')):
            return None
        if store.valid(request.cookies.get(COOKIE)):
            return None
        if path.startswith('/api/') or request.method!='GET':
            return JSONResponse({'detail':'Unlock NEXEN first.','login':'/login'},status_code=401)
        next_path=path if path in SUPPORTED_DESTINATIONS else '/'
        return RedirectResponse('/login?next='+next_path,status_code=303)

    return gate
