const el=id=>document.getElementById(id);
let packet=null, prepared=null, answer='', busy=false;
async function api(path,body,timeout=15000){
  const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);
  try{const response=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,signal:controller.signal});
    if(response.status===401)throw Error('Unlock NEXEN to continue.');
    const data=await response.json();if(!response.ok)throw Error(typeof data.detail==='string'?data.detail:'NEXEN could not complete that request.');return data;
  }finally{clearTimeout(timer)}
}
function textNode(tag,text){const item=document.createElement(tag);item.textContent=text;return item}
function validContextPacket(value){return !!value&&typeof value==='object'&&!Array.isArray(value)&&typeof value.text==='string'&&Array.isArray(value.citations)&&!!value.flow&&Array.isArray(value.flow.stages)&&value.flow.stages.every(stage=>stage&&typeof stage==='object'&&['id','label','status','tooltip'].every(key=>typeof stage[key]==='string'))}
function controls(){el('retrieve').disabled=busy;el('generate').disabled=busy||!packet||!el('model').value;el('question').disabled=busy;el('pool').disabled=busy;el('model').disabled=busy;el('save').disabled=busy||!answer;}
function showFlow(flow,modelDraft=false){el('flow').replaceChildren(...flow.stages.map(stage=>{const item=textNode('li','');item.append(textNode('strong',stage.label),textNode('small',modelDraft&&['suggestions','answer','combined'].includes(stage.id)?'Model draft · requires review':stage.status.replaceAll('_',' ')));item.title=stage.tooltip;item.tabIndex=0;return item}))}
function invalidate(){packet=null;prepared=null;answer='';el('answer').textContent='Request changed. Retrieve its relevant knowledge again.';el('save-status').textContent='';controls()}
el('question').addEventListener('input',invalidate);el('pool').addEventListener('change',invalidate);el('model').addEventListener('change',controls);
el('retrieve').onclick=async()=>{const query=el('question').value.trim();if(!query){el('status').textContent='Describe the task first.';return}busy=true;packet=null;answer='';controls();el('status').textContent='Looking in shared memory…';
  try{packet=await api('/api/memory/context',{query,pool:el('pool').value,task_type:'workflow'},30000);prepared={query,pool:el('pool').value};showFlow(packet.flow);el('evidence').textContent=packet.text;el('sources').replaceChildren(...packet.citations.map(source=>{const item=textNode('div','');item.className='source';item.append(textNode('strong',source.title||source.source_id||'Indexed source'),textNode('p','Origin: '+JSON.stringify(source)));return item}));if(!packet.citations.length)el('sources').textContent='No matching indexed evidence. Add relevant material or refine the subject.';el('status').textContent=packet.flow.subject+' · '+packet.data_sufficiency.replaceAll('_',' ')+'. '+(packet.warnings||[]).join(' ');el('answer').textContent='Context is prepared. The local model can now draft the combined guide.';
  }catch(error){packet=null;el('status').textContent=error.name==='AbortError'?'Retrieval timed out. No model request was submitted.':error.message}finally{busy=false;controls()}};
el('generate').onclick=async()=>{if(!packet||!prepared)return;busy=true;controls();el('status').textContent='Local AI is combining the evidence into a draft…';
  try{const data=await api('/api/lab/chat',{model:el('model').value,text:prepared.query,pool:prepared.pool,workflow:true},135000);const next=data?.context_packet;if(!validContextPacket(next)||typeof data.text!=='string'||!data.text.trim())throw Error('The local model returned an unusable context packet. The displayed context is preserved.');answer=data.text;packet=next;el('evidence').textContent=packet.text;el('answer').textContent=answer;showFlow(packet.flow,true);el('status').textContent='Local model draft ready. No task was executed.';
  }catch(error){el('status').textContent=error.name==='AbortError'?'Model request timed out. The displayed context is preserved.':error.message}finally{busy=false;controls()}};
el('save').onclick=async()=>{if(!answer||!prepared)return;busy=true;controls();try{const body='Knowledge guide draft for: '+prepared.query+'\n\n'+answer+'\n\nReferences: '+JSON.stringify(packet.citations)+'\nGenerated local suggestion; no execution verified.';if(body.length>4000)throw Error('This guide exceeds the task length limit. Shorten the request and generate a smaller guide before saving.');const result=await api('/api/hub/request',{text:body});el('save-status').textContent='Planned task saved: '+(result.id??result.request_id??'see Tasks');answer='';}catch(error){el('save-status').textContent=error.message}finally{busy=false;controls()}};
Promise.allSettled([api('/api/memory/pools').then(data=>{for(const pool of data.pools){const option=textNode('option',pool.label);option.value=pool.id;el('pool').append(option)}}).catch(error=>el('status').textContent=error.message),api('/api/lab/models').then(data=>{el('model').replaceChildren(...data.models.map(model=>{const option=textNode('option',model.name);option.value=model.name;return option}));if(data.models.some(model=>model.name==='qwen3.5:9b'))el('model').value='qwen3.5:9b';el('model-status').textContent=data.models.length+' installed local models. First loading may take longer.';controls()}).catch(()=>{el('model').replaceChildren(textNode('option','Ollama unavailable'));el('model').value='';el('model-status').textContent='Ollama is unavailable. Knowledge retrieval still works. Check Storage + models for transfer status.';controls()})]);
